domain: brpl20.github.io
url: https://brpl20.github.io

title: ProcStudio Blog
email: contato@procstudio.com.br
description: Sistema de gerenciamento escritório e automatização de documentos.

markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
